produit_service_contact_us:
    path: /nous/contacter
    defaults: { _controller: ProduitServiceBundle:Message:contactus }
produit_service_apropos_denous:
    path: /apropos/denous
    defaults: { _controller: ProduitServiceBundle:Apropos:aproposdenous }
produit_service_assistance_entreprise:
    path: /presentation/formation/{id}
    defaults: { _controller: ProduitServiceBundle:Service:presentationformation }
    requirements:
        id: \d+
produit_service_yourcv_recrutement:
    path: /user/crediter/compte
    defaults: { _controller: ProduitServiceBundle:Recrutement:votredossier }
produit_service_dossier_derecrutement_user:
    path: /dossier/user/ouverture/dossier/recherche/{id}
    defaults: { _controller: ProduitServiceBundle:Recrutement:affichedossieruser }
    requirements:
        id: \d+
produit_service_telechargement_fiche_ouverture_dossier:
    path: /telechargement/fiche/ouverture/dossier/{id}
    defaults: { _controller: ProduitServiceBundle:Recrutement:telechargerlettre }
    requirements:
        id: \d+
produit_service_key_of_product_authentification:
    path: /key/of/product/authentification
    defaults: { _controller: ProduitServiceBundle:Curentwebsite:curentwebsite }
produit_service_affiche_contenu_detaille_article_blog:
    path: /affiche/contenu/detaill/article/blog/{id}
    defaults: { _controller: ProduitServiceBundle:Service:affichearticle }
    requirements:
        id: \d+
produit_service_ajouter_commentaire_article_user:
    path: /sujets/forum/{id}/{page}
    defaults: { _controller: ProduitServiceBundle:Service:ajoutersujetforum, page: 1 }
    requirements:
        id: \d+
        page: \d+
produit_service_interventions_sujets_courant:
    path: /interventions/sujets/courant/{id}/{page}
    defaults: { _controller: ProduitServiceBundle:Service:interventionsujet, page: 1 }
    requirements:
        id: \d+
        page: \d+
produit_service_supprimer_commentaire_courant_article:
    path: /supprimer/commentaire/courant/article/{id}
    defaults: { _controller: ProduitServiceBundle:Service:supprimercommentaire }
    requirements:
        id: \d+
produit_service_delete_intervention_sujet:
    path: /delete/intervention/sujet/{id}
    defaults: { _controller: ProduitServiceBundle:Service:deleteintervention }
    requirements:
        id: \d+
produit_service_toute_actualite_entreprise:
    path: /formateurs
    defaults: { _controller: ProduitServiceBundle:Service:formateurstruct }
produit_service_liste_formateur_struct:
    path: /liste/formateurs/struct/{page}
    defaults: { _controller: ProduitServiceBundle:Service:listeformateur, page: 1 }
    requirements:
        page: \d+
produit_service_download_video_formation:
    path: /download/video/formation/{id}
    defaults: { _controller: ProduitServiceBundle:Service:downloadvideoformation }
    requirements:
        id: \d+
produit_service_visiter_notre_blog:
    path: /formations
    defaults: { _controller: ProduitServiceBundle:Service:nosformations }
produit_service_all_formation_struct:
    path: /all/formations/struct/{page}
    defaults: { _controller: ProduitServiceBundle:Service:listeformation, page: 1 }
    requirements:
        page: \d+
produit_service_add_formation_panier:
    path: /user/add/formation/panier/{id}
    defaults: { _controller: ProduitServiceBundle:Service:addformationpanier }
    requirements:
        id: \d+
produit_service_forum_site:
    path: /az/forum
    defaults: { _controller: ProduitServiceBundle:Service:accueilforum }
produit_service_recherche_forum:
    path: /service/recherche/forum/{donnee}{page}
    defaults: { _controller: ProduitServiceBundle:Service:rechercheforum, donnee: '', page: 1 }
    requirements:
        page: \d+