parameters:
    nbcategorie: 10
    nbsouscategorie: 7
    nbslide: 7
    nbproduitsouscat: 10
    nbimgparproduit: 5
    siteweb: http://cm.africexplorer.com/
    conditionuserlink: http://cm.africexplorer.com/condition/
    sitename: Africexplorer Cameroun
    emailadmin: noel.kenfack@yahoo.fr
    username: az_e-learning
    password: africexplorer
    tel: 695689632
    bp: 1245
    repeattime: 24
    notemin: 5
    noteminexo: 5
    orangemoney: 695689632
    mtnmobile: 675689632
#La variable repeattime indique le nombre d'heure qu'il faut attendre pour reprendre un questionnaire echoué.  # La variable notemin la note minimale pour fermer un questionnaire.
#    general_service.example.class: General\ServiceBundle\Example

services:
#    general_service.example:
#        class: %general_service.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    general_service.servicetext:
        class: General\ServiceBundle\Servicetext\GeneralServicetext
    general_service.myuserauthentification:
        class: General\ServiceBundle\UserAuthentification\Curentwebsite
        arguments: [@request,@doctrine.orm.entity_manager,%curentwebsite%]
        scope: request
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }